spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: auth-gateway
  profiles:
    active: ${PROFILES_ACTIVE:local}

# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring.xml